### ISSUE TITLE
Rustscan nd corsy 

### ISSUE THREAD

**Issue by Sim4n6** [supr4s/WebHackingTools#8]
How about adding rustscan please? And corsy?

**Comment by Sim4n6** [comment]
- [Corsy](https://github.com/s0md3v/Corsy)
 - [RustScan](https://github.com/RustScan/RustScan)

**Comment by supr4s** [comment]
Hi @Sim4n6 

Thanks for the suggestion!
They are in my list to add on the next release :)

Thanks you !

**Comment by supr4s** [comment]
Corsy added, Rustscan not. Maybe later but not for now !

**Comment by Sim4n6** [comment]
👍🏾
