### ISSUE TITLE
ShellCheck the code + Check whether a tool is installed

### ISSUE THREAD

**Issue by Sim4n6** [supr4s/WebHackingTools#9]
I would like to make two PRs but I need your opinion first.
1. ShellCheck the shell code and make it a little bit different.
2. Check if a tool is installed before proceeding with a download install.

what do you think please ?

**Comment by supr4s** [comment]
Hi @Sim4n6 ,

Sorry for the late response.
Sounds like a good idea ! I would like your PRs :) 

Thanks !

**Comment by supr4s** [comment]
I'll re-open the issue if you don't mind.

**Comment by Sim4n6** [comment]
nope no PR
